### ISSUE TITLE
Discrepencies in Documentation on CMS164v7, HIV Linkage to Care, and CMS 277v0 

### ISSUE THREAD

**Issue by joshua-hiltunen** [drajer-health/uds-plus#17]
Re: Data presented at https://fhir.org/guides/hrsa/uds-plus/dataelements.html

The sections for CMS 164v7, HIV Linkage to Care, and CMS 277v0 all refer to elements that look like elements that were documented using different language elsewhere.  Are these equivalents, or are they representing different sets of info?  Should the language on these be aligned?  List below attempting to map between the terminology used.

**Diagnosis**
| CMS164v7, HIV Linkage to Care, CMS277v0 | CMS124v11, etc... |
|--------|--------|
| Diagnosis | <is this supposed to be the three non-aligned fields?> |
| Diagnosis Time (OnsetDateTime) | Diagnosis - OnsetDateTime |
|  | Diagnosis - AbatementDateTime |
|  | Diagnosis - Clinical Status | 
|  | Diagnosis - Code |

**Encounter**
| CMS164v7, HIV Linkage to Care, CMS277v0 | CMS124v11, etc... |
|--------|--------|
| Discharge Disposition | Encounter, Performed - Discharge Disposition |
|  Encounter Diagnosis | Encounter, Performed - Diagnosis |
| | Encounter, Performed - Diagnosis Rank |
| Encounter Participant | Encounter, Performed - Participant |
| Encounter Performed | |
| Encounter Period | Encounter, Performed - Period |
| Encounter Type | _not represented in other Encounter documentation, though Encounter.type is MUST SUPPORT and cardinality 1..*  Match to other elements would be 'Encounter, Performed - Type'_ |

**Intervention, Order**
| CMS164v7, HIV Linkage to Care, CMS277v0 | CMS124v11, etc... |
|--------|--------|
| Intervention Order - Referral| Intervention, Order - AuthoredOn |
| | Intervention, Order - Code |

**Procedure**
| CMS164v7, HIV Linkage to Care, CMS277v0 | CMS124v11, etc... |
|--------|--------|
| Procedure Performed | Procedure, Performed - Code | 
| | Procedure, Performed - Recorded |
| Procedure Performed DateTime | Procedure, Performed - DateTime/Period |

**Comment by nbashyam** [comment]
The above examples are all representing different types of information and are not the same. The semantics and what they represent are different.

**Comment by joshua-hiltunen** [comment]
I think what I was getting at is the Resources involved are the same, the distinction here is on the applicable Code sets being searched for (each measure is looking for particular sets of conditions/observations/procedures which are identified by the resource's coding).  

This page is referring specifically to the FHIR constructs, not the codes that are being queried for.  The ones I've pointed out above refer to the same locations (fhirpath?) within the same sets of FHIR resources by different names.
