### ISSUE TITLE
Bulk Data IG _since Requirement 

### ISSUE THREAD

**Issue by joshua-hiltunen** [drajer-health/uds-plus#20]
Certifying to CURES did not require support for Bulk Data 2.0.0, and the EHRs I'm working with certified to US Core 4.0.0/USCDIv1/Bulk Data 1.0.1.  

However, I also don't see the _since argument getting used or indicated for use other than as a requirement (in a vacuum) on https://fhir.org/guides/hrsa/uds-plus/spec.html. 

What is your intended usage around this argument?  The receiver presumably doesn't interact with the argument, and neither the Data Submitter nor Trust Service Provider sections refer to it at all.  Is _since actually required?  If yes, is there additional documentation on your expected usage thereof?

**Comment by nbashyam** [comment]
The _since parameter is part of the 1.0.1 Bulk Data FHIR IG. 
The reason for specifying that it needs to be supported was to help the Data Source implementers in determining the look back period for exporting the necessary data for the current reporting year. Data Sources can export without using the Bulk Export in which case the requirement would not apply.

**Comment by joshua-hiltunen** [comment]
Yeah, I think in the documentation I saw _since as an optional argument in 1.0.1.  2.0.0 made it required, which is the distinction I was making.  

So the requirement for support of _since is more like implementation guidance for Data Submitters, or for EHRs that are working with a data submitter.  I had definitely considered how we'd time box information, but because we're setting up the bulk job as the submitter ourselves, I was going to leverage the date based query parameters (on the resources where that made sense) as the means by which we could compartmentalize on the reporting period.
