### ISSUE TITLE
Resubmission and Error Feedback

### ISSUE THREAD

**Issue by joshua-hiltunen** [drajer-health/uds-plus#22]
Is the only feedback mechanism for errors during submission the Error response after the $import completes with details?   Are there any additional channels (letter, email, etc...) that this information is communicated back to involved providers?  

What I'm trying to establish here is whether we have a single mechanism post-UDS+ or if providers will continue to receive the notifications that they've previously received while submitting for UDS along the avenues they're familiar with.

**Comment by nbashyam** [comment]
This will be addressed by HRSA on other channels such as the UTC meetings and On-boarding discussions and Office Hours. The IG will not be able to specify the mechanisms beyond what is already specified. 
Please bring it up in the other forums that exist for UDS+ for a discussion on the ticket.
