### ISSUE TITLE
Zip Code De-Identification - HHS guide is out of date

### ISSUE THREAD

**Issue by anthonygalba** [drajer-health/uds-plus#35]
In the HHS [Guidance on De-identification of Protected Health Information (hhs.gov)](https://www.hhs.gov/sites/default/files/ocr/privacy/hipaa/understanding/coveredentities/De-identification/hhs_deid_guidance.pdf) document, they list the specific zip codes with small populations that should be masked:
![image](https://github.com/drajer-health/uds-plus/assets/153321284/5c546a5b-5a86-4231-84d6-70b1c765979a)
However, that data is from the 2000 Census, which is quite out of date now.
Is there an updated version of this guidance that uses 2020 census information we can reference?
If not, can HRSA provide guidance on which zip code need to be de-identified using more recent census data?

**Comment by rachelfried** [comment]
Great question.  Please see the UDS+ Office Hours FAQ, which lists the updated 2020 Census zip codes, provided by HRSA (18 zip codes), which are being validated against by the IG v1.0.1.  Copied here for ease of access:

202
753
205
204
821
203
059
772
692
893
036
823
102
879
556
884
878
369
