### ISSUE TITLE
Do we need to create a new identifier to map between identified and de-identified data?

### ISSUE THREAD

**Issue by nisk90** [drajer-health/uds-plus#39]
In the UDS+ FHIR IG, one of the requirements for a Trust Service Provider is "The Trust Service Provider SHALL create an identifier that is retained internally to link between identifiable and de-identifiable data."

1.   What would be the use-case for which this information would be used?
2.   What is the meaning of "..an identifier" - Is it expected that the EHR vendors should Madatorily create a 'unique identifier' that maps the identified and de-identifiable data points
3.   What is the meaning of "..is retained" - Is it expected that the EHR vendor should save the above identifier in a DB or some other source? If yes, for how long?

**Comment by joshua-hiltunen** [comment]
Was about to add a new issue, but this is basically in the same lane as what I was going to ask.  I'm looking for additional clarification on ID Generation.  The UDS+ Patient Resource profile indicates:

> Id Generation
> 
> The original patient resource id should not be included in the De-identified patient instance. Instead a new id should be created and provided as part of the FHIR resource. This Data Submitter should be capable of using the generated id to relink the data to the original patient. All resource references to the Patient submitted as part of the UDS+ report should refer to newly generated de-identified id.

My question is, does the new ID need to remain consistent across years for the same patient.  In other words, if you get data for Patient X in year 2023 with id <a_guid>, do you expect the same "deidentified" <a_guid> id for Patient X in year 2024.  Or can each reporting period represent a patient with an identifier specific to that reporting period?

Fundamentally are you trying to track the deidentified patients across the years?  Or look at each year in isolation?

**Comment by nbashyam** [comment]
Tracking Across years is one of the goals.

**Comment by joshua-hiltunen** [comment]
So however the GUID transforms needs to be consistent year over year.

**Comment by nisk90** [comment]
I have the same questoin as [joshua-hiltunen](https://github.com/joshua-hiltunen).

Can we please get a response to "if we're salting and hashing to generate the new ID, does our ability to retrieve the ID constitute retention, even if the mapping from original ID to new ID is not stored?"

**Comment by nbashyam** [comment]
Yes, as long as you can track the data back to the Identifiable resource, it does not need to be stored
