### ISSUE TITLE
Procedure.statusReason use case

### ISSUE THREAD

**Issue by anthonygalba** [drajer-health/uds-plus#40]
How is the Procedure.statusReason data element supposed to be used?

I noticed on the US Core procedure resource, it has example codes that are procedure not performed reason SNOMED codes.
Is this supposed to be used to represent the negation rationale for the Intervention, Performed templates in Table 6B line 13? 

That is the only places in current UDS measures where we'd care about a procedure that did not happen.
I think for every other procedure in UDS the status would be "completed" otherwise it would not be a performed procedure and not counted by the eCQM measures.

**Comment by nbashyam** [comment]
This is correct, it is used for negation indications. There are a couple of measures where the negation is required.

**Comment by anthonygalba** [comment]
Thanks!
