### ISSUE TITLE
Regarding length of URL for getting publickey  allowed while registering the practice in HRSA + UDS-Plus Program

### ISSUE THREAD

**Issue by Veeruathena** [drajer-health/uds-plus#65]
Hi All,

I have question regarding the max size limit  of HTML control (TextBox or TextArea)  to capture the URL,(which is used to get the PublicKey) while registering the new practice in HRSA.  I am asking this question since we are planning to use CloudFront Signed URL to protect it from use case specific to HRSA.   Since it is a CloudFront Signed URL, length is more than 500  characters and max can be 1000.  Please confirm what is the allowed size to capture this URL during new client registration in HRSA.

Regards
Veeru

**Comment by nbashyam** [comment]
We have not encountered any specific issues so far with URLs and their sizes. we encourage you to participate in the cohort testing to ensure there is no issues in the future.
