### ISSUE TITLE
How to identify Mandatory/Must Support Elements in UDS+ FHIR resources

### ISSUE THREAD

**Issue by nisk90** [drajer-health/uds-plus#66]
How do we identify which FHIR resource attributes are needed/mandatory for UDS+ submission. 

There are attributes which have the 'S' (Must Support) label but their cardinality is 0..1. Examples below

<img width="1122" alt="Screenshot 2024-05-15 at 5 58 20 PM" src="https://github.com/drajer-health/uds-plus/assets/164319675/510b4fc4-cd5e-4386-b885-ddf388b6f446">

- Are such attributes Optional or Mandatory? 
- What is the significance of 'S'?

**Comment by nisk90** [comment]
@nbashyam

**Comment by nbashyam** [comment]
The definition of "S" (SUPPORTED or MUST SUPPORT) is present in the IG at the below link
https://fhir.org/guides/hrsa/uds-plus/spec.html#must-support-definition 
Please let us know if you have any further questions.
