### ISSUE TITLE
Link issue with sexual orientation codes

### ISSUE THREAD

**Issue by rachelfried** [drajer-health/uds-plus#75]
Pointed out in a call that the sexual orientation link to the code sets might have broken during updates to UDS+ FHIR IG v1.1.0.  To be reviewed:

http://hl7.org/fhir/us/core/ValueSet/us-core-sexual-orientation
 
https://fhir.org/guides/hrsa/uds-plus/ValueSet-uds-plus-sexual-orientation-codes.html

Uds Plus Sexual Orientation Codes - HRSA 2023 Uniform Data System (UDS) Patient Level Submission (PLS) (UDS+) FHIR IG v1.1.0

**Comment by nbashyam** [comment]
The Link
https://hl7.org/fhir/us/core/STU6.1/ValueSet-us-core-sexual-orientation.html has the right value set.
This is the value set canonical URL : 
http://hl7.org/fhir/us/core/ValueSet/us-core-sexual-orientation
The UDSPlus IG is aligned with US Core 6.1.0 hence the above link has to be used appropriately.

**Comment by nisk90** [comment]
@nbashyam  can ASKU, OTH, asked-declined, and UNK code also be used to as codes for sexual-orientation? or is NASK the only valid code that can be used?
